# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d799be800228679c0b9ee0298a824e6d594d0237a9e70a62f52223bca09af4330b89046f5a0b6135174d0ee5529a8ea52edcc4496ef853745609c4b3dc116c77
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>


test:
  secret_key_base: 863e287794e88ae319ca845c0a25061a2ea9695961c5a04e30a1565c7cce3cfde7d31df16ec2f7f1cea06686c2d5fe32bd771e4f5aa9310971765b91559f94c3

# Do not keep production secrets in the repository,
# instead   aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
